export enum Chip {
  PICTURE='PICTURE',
  VIDEO='VIDEO',
  TEXT='TEXT',
  JOB='JOB',
  FORM='FORM',
  SHOPPING_ITEM='SHOPPING_ITEM',
  SHOPPING_CARD='SHOPPING_CARD',
  SETTINGS='SETTINGS',
  DOMAINS='DOMAINS',
  MOVE_RIGHT='MOVE_RIGHT',
  MOVE_LEFT='MOVE_LEFT',
  HOTEL_SEARCH='HOTEL_SEARCH'
}
