export enum SideMenuType {
    LOCATION = "LOCATION",
    MENU = "MENU",
    ACCESSORIES = "ACCESSORIES",
    GALLERY = "GALLERY",
    RESERVATIONS = "RESERVATIONS",
    SEARCH = "SEARCH",
    JOB_OVERVIEW = "JOB_OVERVIEW",
    JOB_QUALIFICATIONS = "JOB_QUALIFICATIONS",
    JOB_ABOUT_COMPANY = "JOB_ABOUT_COMPANY",
    JOB_SIMILAR_JOBS = "JOB_SIMILAR_JOBS",
}
